/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ElxButton {
        "radius": 'small' | 'medium' | 'large';
        "size": 'small' | 'medium' | 'large';
        "variant": 'primary' | 'secondary';
    }
}
declare global {
    interface HTMLElxButtonElement extends Components.ElxButton, HTMLStencilElement {
    }
    var HTMLElxButtonElement: {
        prototype: HTMLElxButtonElement;
        new (): HTMLElxButtonElement;
    };
    interface HTMLElementTagNameMap {
        "elx-button": HTMLElxButtonElement;
    }
}
declare namespace LocalJSX {
    interface ElxButton {
        "radius"?: 'small' | 'medium' | 'large';
        "size"?: 'small' | 'medium' | 'large';
        "variant"?: 'primary' | 'secondary';
    }
    interface IntrinsicElements {
        "elx-button": ElxButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "elx-button": LocalJSX.ElxButton & JSXBase.HTMLAttributes<HTMLElxButtonElement>;
        }
    }
}
